Add Docker deployment docs
arctic-hen7/perseus pull request #98
Opened 2021-12-22 10:08 UTC by phaleth

`esbuild` and `wasm-opt` optimization steps aren't explained and also there isn't any css optimization `esbuild` step included as hello world examples don't yet contain any css file, but I think this is good enough for starters. Feel free to change anything, even any of the wording used, or suggest a change.

2021-12-23 08:05 UTC, arctic-hen7 requested changes
Really great work, thanks so much! Just some minor things on phrasing, and then I'd like all the `Dockerfile`s to be in `<details>` blocks for better scrolling support (otherwise people will have to scroll through a huge amount of code to get to what they want).

2021-12-23 08:05 UTC, arctic-hen7 commented on docs/next/en-US/deploying/docker.md
> +# Docker Deployment
Could you please apply the same changes I requested for the v0.3.x version here?

2021-12-27 13:14 UTC, phaleth commented
I kind of just copy pasted all the suggested changes. Be aware that I can't run the website locally anymore cause of `concurrently`. The error is posted #97.

2021-12-27 22:00 UTC, arctic-hen7 requested changes
Just some spacing issues that maybe didn't go through properly. We need to have newlines after the `<summary>` blocks and before the closing `</details>`, otherwise the Markdown won't render properly. Otherwise great, thanks!

2021-12-30 12:52 UTC, phaleth commented on docs/next/en-US/deploying/docker.md
> +# Docker Deployment
Not sure what you mean here.

2021-12-30 20:27 UTC, arctic-hen7 commented on docs/next/en-US/deploying/docker.md
> +# Docker Deployment
Sorry, that was meant for the whole file. All good now!

2021-12-30 20:28 UTC, arctic-hen7 approved these changes
Great, thanks!

2022-01-02 07:57 UTC, merged